<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder2 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Ajay Maurya',
                'email' => 'a@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'mobile' => '9876543210',
                'dob' => '1990-05-15',
                'gender' => 'Male',
                'bio' => 'Lorem ipsum dolor sit amet.',
                'is_admin' => 1,
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rita Sharma',
                'email' => 'b@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'mobile' => '9876543211',
                'dob' => '1992-08-20',
                'gender' => 'Female',
                'bio' => 'Lorem ipsum dolor sit amet.',
                'is_admin' => 0,
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vikram Singh',
                'email' => 'u@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'mobile' => '9876543212',
                'dob' => '1988-12-05',
                'gender' => 'Male',
                'bio' => 'Lorem ipsum dolor sit amet.',
                'is_admin' => 0,
                'is_active' => 0,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Priya Kapoor',
                'email' => 'priya@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'mobile' => '9876543213',
                'dob' => '1995-03-12',
                'gender' => 'Female',
                'bio' => 'Lorem ipsum dolor sit amet.',
                'is_admin' => 0,
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rahul Mehta',
                'email' => 'rahul@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'mobile' => '9876543214',
                'dob' => '1991-11-25',
                'gender' => 'Male',
                'bio' => 'Lorem ipsum dolor sit amet.',
                'is_admin' => 0,
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Neha Jain',
                'email' => 'neha@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'mobile' => '9876543215',
                'dob' => '1993-07-08',
                'gender' => 'Female',
                'bio' => 'Lorem ipsum dolor sit amet.',
                'is_admin' => 0,
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Karan Verma',
                'email' => 'karan@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'mobile' => '9876543216',
                'dob' => '1989-01-30',
                'gender' => 'Male',
                'bio' => 'Lorem ipsum dolor sit amet.',
                'is_admin' => 0,
                'is_active' => 0,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sanya Gupta',
                'email' => 'sanya@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'mobile' => '9876543217',
                'dob' => '1994-09-14',
                'gender' => 'Female',
                'bio' => 'Lorem ipsum dolor sit amet.',
                'is_admin' => 0,
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manish Sharma',
                'email' => 'manish@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'mobile' => '9876543218',
                'dob' => '1987-06-20',
                'gender' => 'Male',
                'bio' => 'Lorem ipsum dolor sit amet.',
                'is_admin' => 0,
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tanya Singh',
                'email' => 'tanya@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'mobile' => '9876543219',
                'dob' => '1996-02-28',
                'gender' => 'Female',
                'bio' => 'Lorem ipsum dolor sit amet.',
                'is_admin' => 0,
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
